<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="K_Anderson" failures="1" tests="12" name="edgeTest" time="176.193" errors="0" timestamp="2025-05-19T11:41:41 EDT">
  <testcase classname="testCases.TC01_LaunchApplication" name="testLaunchApplication" time="1.111"/>
  <testcase classname="testCases.TC03_AddToCart" name="testAddToCart" time="7.882"/>
  <testcase classname="testCases.TC05_AddToWishList" name="testAddToWishList" time="15.812"/>
  <testcase classname="testCases.TC06_AddAffiliate" name="testAddAffiliate" time="8.912"/>
  <testcase classname="testCases.TC02_Login" name="testLogin" time="4.573"/>
  <testcase classname="testCases.TC02_Login" name="testLogin" time="3.593"/>
  <testcase classname="testCases.TC02_Login" name="testLogin" time="3.739"/>
  <testcase classname="testCases.TC02_Login" name="testLogin" time="3.026"/>
  <testcase classname="testCases.TC02_Login" name="testLogin" time="3.279"/>
  <testcase classname="testCases.TC04_CompletePurchase" name="testCompletePurchase" time="23.108">
    <skipped/>
  </testcase> <!-- testCompletePurchase -->
  <testcase classname="testCases.TC04_CompletePurchase" name="testCompletePurchase" time="16.003">
    <skipped/>
  </testcase> <!-- testCompletePurchase -->
  <testcase classname="testCases.TC04_CompletePurchase" name="testCompletePurchase" time="12.177">
    <failure type="java.lang.AssertionError" message="Test failed due to unexpected exception.">
      <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at testCases.TC04_CompletePurchase.testCompletePurchase(TC04_CompletePurchase.java:81)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testCompletePurchase -->
</testsuite> <!-- edgeTest -->
